title: Oddly's Blog
description: Recipes, art, and everything in between
baseurl: ""
url: "https://oddly-augmented.github.io"

permalink: /blog/:slug/

plugins:
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"