title: Oddly's Blog
tagline: A personal blog for recipes, Art, and whatever else I'm into.
description: A personal blog covering recipes, art, and everyday creativity by Mairekk.
baseurl: ""
url: "https://oddly-augmented.github.io"


permalink: /blog/:slug/


plugins:
  - jekyll-paginate
  - jekyll-sitemap


paginate: 6
paginate_path: "/blog/page:num/"