title: Oddly's Blog
tagline: A personal blog for recipes, Art, and whatever else I'm into.
description: Blogs about Recipes, art, and everything in between
baseurl: ""
url: "https://oddly-augmented.github.io"


permalink: /blog/:slug/


plugins:
  - jekyll-paginate


paginate: 6
paginate_path: "/blog/page:num/"