# Images blacklist
blacklist:
  - Temp_Pic.png

# Custom alt text
alt:
  Blender_lowpoly.png: "Low poly render made in Blender"
  Jam_on_toats.jpg: "Jam on toast, a quick breakfast"
  Tomato_Tart.jpg: "Homemade tomato tart"
  Brozeno_and_Tomato.jpg: "Branzino with tomato beurre blanc, French pico de gallo, and crispy leek-crusted sunchokes"
  Chese_Board.jpg: "Cheese board with fruit, nuts and jams"
  Chicken.jpg: "Confit chicken leg served with a wild mushrooms, pommes purée and rich port sauce"